# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ConvertToMd < Formula
  desc "Convert webpages to Markdown from your terminal."
  homepage "https://github.com/tomerwave/convert-to.md"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tomerwave/convert-to.md/releases/download/v0.1.0/convert-to-md_0.1.0_Darwin_x86_64"
      sha256 "21efaa5ea3991b68f05f0bd3f48cf1e7916e9569b088140218e36fe7399c5e4b"

      define_method(:install) do
        bin.install "convert-to-md"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tomerwave/convert-to.md/releases/download/v0.1.0/convert-to-md_0.1.0_Darwin_arm64"
      sha256 "87e72ebedbdf31515f791b35bb501d08c88df19c17d438d688879295525c9934"

      define_method(:install) do
        bin.install "convert-to-md"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tomerwave/convert-to.md/releases/download/v0.1.0/convert-to-md_0.1.0_Linux_x86_64"
      sha256 "434796978bc4dc21758002ad57aa6a8cd1f503c7bf16593dd27eaea2d2c15610"
      define_method(:install) do
        bin.install "convert-to-md"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tomerwave/convert-to.md/releases/download/v0.1.0/convert-to-md_0.1.0_Linux_arm64"
      sha256 "66e31d74dac38d61ad50e9061cab41dc6e7c151ea633d411e77f65f9e6470491"
      define_method(:install) do
        bin.install "convert-to-md"
      end
    end
  end
end
